/<?php

// This file was generated by running "composer dump-env prod"

$db_url = "mysql://root:".urlencode("FjD#47%5mA")."@127.0.0.1:3306/420343_nrange?serverVersion=5.7";
return array (
  'APP_ENV' => 'prod',
  'DATABASE_URL' => $db_url
);
